name: Pull request

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:
    branches: [develop]

env:
  work_directory: ./my-app

jobs:
  check_pull_request:
    name: Check pull request
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node_version: [16.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    defaults:
      run:
        working-directory: ${{env.work_directory}}

    steps:
      - name: Clone files
        uses: actions/checkout@v3

      - name: Add node  ${{matrix.node_version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm run test

      - name: Run lint
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Show message
        run: echo "Good job!"
